From node:16-alpine as builder
ARG DOMAIN

ENV REACT_APP_BACKEND_URL=${DOMAIN}

WORKDIR /app

# install app dependencies
# copies package.json and package-lock.json to Docker environmenta
COPY frontend/package*.json ./

# Installs all node packages
RUN npm install

# Copies everything over to Docker environment
COPY frontend/ .

RUN npm run build

#Stage 2
#######################################
#pull the official nginx:stable base image
FROM nginx:stable

WORKDIR /usr/share/nginx/html
# Remove default nginx static resources
# RUN rm -rf ./*
# Copies static resources from builder stage
COPY --from=builder /app/build .
# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]